package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Adminlogginsession generated by hbm2java
 */
public class Adminlogginsession  implements java.io.Serializable {


     private Integer idAdminLogginSession;
     private Adminlogin adminlogin;
     private Date inTime;
     private Date outTime;
     private String ipaddress;

    public Adminlogginsession() {
    }

	
    public Adminlogginsession(Adminlogin adminlogin) {
        this.adminlogin = adminlogin;
    }
    public Adminlogginsession(Adminlogin adminlogin, Date inTime, Date outTime, String ipaddress) {
       this.adminlogin = adminlogin;
       this.inTime = inTime;
       this.outTime = outTime;
       this.ipaddress = ipaddress;
    }
   
    public Integer getIdAdminLogginSession() {
        return this.idAdminLogginSession;
    }
    
    public void setIdAdminLogginSession(Integer idAdminLogginSession) {
        this.idAdminLogginSession = idAdminLogginSession;
    }
    public Adminlogin getAdminlogin() {
        return this.adminlogin;
    }
    
    public void setAdminlogin(Adminlogin adminlogin) {
        this.adminlogin = adminlogin;
    }
    public Date getInTime() {
        return this.inTime;
    }
    
    public void setInTime(Date inTime) {
        this.inTime = inTime;
    }
    public Date getOutTime() {
        return this.outTime;
    }
    
    public void setOutTime(Date outTime) {
        this.outTime = outTime;
    }
    public String getIpaddress() {
        return this.ipaddress;
    }
    
    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress;
    }




}


