package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Adminlogin generated by hbm2java
 */
public class Adminlogin  implements java.io.Serializable {


     private Integer idAdminLogin;
     private Loginstatus loginstatus;
     private String adminUsername;
     private String adminPassword;
     private Set<Adminlogginsession> adminlogginsessions = new HashSet<Adminlogginsession>(0);

    public Adminlogin() {
    }

	
    public Adminlogin(Loginstatus loginstatus) {
        this.loginstatus = loginstatus;
    }
    public Adminlogin(Loginstatus loginstatus, String adminUsername, String adminPassword, Set<Adminlogginsession> adminlogginsessions) {
       this.loginstatus = loginstatus;
       this.adminUsername = adminUsername;
       this.adminPassword = adminPassword;
       this.adminlogginsessions = adminlogginsessions;
    }
   
    public Integer getIdAdminLogin() {
        return this.idAdminLogin;
    }
    
    public void setIdAdminLogin(Integer idAdminLogin) {
        this.idAdminLogin = idAdminLogin;
    }
    public Loginstatus getLoginstatus() {
        return this.loginstatus;
    }
    
    public void setLoginstatus(Loginstatus loginstatus) {
        this.loginstatus = loginstatus;
    }
    public String getAdminUsername() {
        return this.adminUsername;
    }
    
    public void setAdminUsername(String adminUsername) {
        this.adminUsername = adminUsername;
    }
    public String getAdminPassword() {
        return this.adminPassword;
    }
    
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword;
    }
    public Set<Adminlogginsession> getAdminlogginsessions() {
        return this.adminlogginsessions;
    }
    
    public void setAdminlogginsessions(Set<Adminlogginsession> adminlogginsessions) {
        this.adminlogginsessions = adminlogginsessions;
    }




}


