package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0



/**
 * Adminprivilages generated by hbm2java
 */
public class Adminprivilages  implements java.io.Serializable {


     private Integer idAdminPrivilages;
     private Interfaces interfaces;

    public Adminprivilages() {
    }

    public Adminprivilages(Interfaces interfaces) {
       this.interfaces = interfaces;
    }
   
    public Integer getIdAdminPrivilages() {
        return this.idAdminPrivilages;
    }
    
    public void setIdAdminPrivilages(Integer idAdminPrivilages) {
        this.idAdminPrivilages = idAdminPrivilages;
    }
    public Interfaces getInterfaces() {
        return this.interfaces;
    }
    
    public void setInterfaces(Interfaces interfaces) {
        this.interfaces = interfaces;
    }




}


