package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0



/**
 * Advertisement generated by hbm2java
 */
public class Advertisement  implements java.io.Serializable {


     private Integer idAdvertisement;
     private String description;
     private String image;
     private String state;

    public Advertisement() {
    }

    public Advertisement(String description, String image, String state) {
       this.description = description;
       this.image = image;
       this.state = state;
    }
   
    public Integer getIdAdvertisement() {
        return this.idAdvertisement;
    }
    
    public void setIdAdvertisement(Integer idAdvertisement) {
        this.idAdvertisement = idAdvertisement;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }




}


