package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Agelimit generated by hbm2java
 */
public class Agelimit  implements java.io.Serializable {


     private Integer idAgeLimit;
     private String ageLimit;
     private Set<Product> products = new HashSet<Product>(0);

    public Agelimit() {
    }

    public Agelimit(String ageLimit, Set<Product> products) {
       this.ageLimit = ageLimit;
       this.products = products;
    }
   
    public Integer getIdAgeLimit() {
        return this.idAgeLimit;
    }
    
    public void setIdAgeLimit(Integer idAgeLimit) {
        this.idAgeLimit = idAgeLimit;
    }
    public String getAgeLimit() {
        return this.ageLimit;
    }
    
    public void setAgeLimit(String ageLimit) {
        this.ageLimit = ageLimit;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


