package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0



/**
 * CartHasStock generated by hbm2java
 */
public class CartHasStock  implements java.io.Serializable {


     private Integer cartHasStockid;
     private Stock stock;
     private Cart cart;
     private Double qty;
     private Double total;

    public CartHasStock() {
    }

	
    public CartHasStock(Stock stock, Cart cart) {
        this.stock = stock;
        this.cart = cart;
    }
    public CartHasStock(Stock stock, Cart cart, Double qty, Double total) {
       this.stock = stock;
       this.cart = cart;
       this.qty = qty;
       this.total = total;
    }
   
    public Integer getCartHasStockid() {
        return this.cartHasStockid;
    }
    
    public void setCartHasStockid(Integer cartHasStockid) {
        this.cartHasStockid = cartHasStockid;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }




}


