package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Casesize generated by hbm2java
 */
public class Casesize  implements java.io.Serializable {


     private Integer idCaseSize;
     private Double caseWidth;
     private Double caseHeight;
     private Double caseWeight;
     private Set<Product> products = new HashSet<Product>(0);

    public Casesize() {
    }

    public Casesize(Double caseWidth, Double caseHeight, Double caseWeight, Set<Product> products) {
       this.caseWidth = caseWidth;
       this.caseHeight = caseHeight;
       this.caseWeight = caseWeight;
       this.products = products;
    }
   
    public Integer getIdCaseSize() {
        return this.idCaseSize;
    }
    
    public void setIdCaseSize(Integer idCaseSize) {
        this.idCaseSize = idCaseSize;
    }
    public Double getCaseWidth() {
        return this.caseWidth;
    }
    
    public void setCaseWidth(Double caseWidth) {
        this.caseWidth = caseWidth;
    }
    public Double getCaseHeight() {
        return this.caseHeight;
    }
    
    public void setCaseHeight(Double caseHeight) {
        this.caseHeight = caseHeight;
    }
    public Double getCaseWeight() {
        return this.caseWeight;
    }
    
    public void setCaseWeight(Double caseWeight) {
        this.caseWeight = caseWeight;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


