package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Casetype generated by hbm2java
 */
public class Casetype  implements java.io.Serializable {


     private Integer idCaseType;
     private String caseType;
     private Set<Product> products = new HashSet<Product>(0);

    public Casetype() {
    }

    public Casetype(String caseType, Set<Product> products) {
       this.caseType = caseType;
       this.products = products;
    }
   
    public Integer getIdCaseType() {
        return this.idCaseType;
    }
    
    public void setIdCaseType(Integer idCaseType) {
        this.idCaseType = idCaseType;
    }
    public String getCaseType() {
        return this.caseType;
    }
    
    public void setCaseType(String caseType) {
        this.caseType = caseType;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


