package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer idClient;
     private Userstatus userstatus;
     private Gender gender;
     private String fname;
     private String lname;
     private String email;
     private String mobileno;
     private String telephoneno;
     private String addressno;
     private String street1;
     private String street2;
     private String street3;
     private Integer points;
     private String image;
     private Set<ClientHasRecoverquestion> clientHasRecoverquestions = new HashSet<ClientHasRecoverquestion>(0);
     private Set<Comment> comments = new HashSet<Comment>(0);
     private Set<Watchlist> watchlists = new HashSet<Watchlist>(0);
     private Set<Userverificationcode> userverificationcodes = new HashSet<Userverificationcode>(0);
     private Set<Clientlogin> clientlogins = new HashSet<Clientlogin>(0);
     private Set<Invoice> invoices = new HashSet<Invoice>(0);
     private Set<Cart> carts = new HashSet<Cart>(0);

    public Client() {
    }

	
    public Client(Userstatus userstatus) {
        this.userstatus = userstatus;
    }
    public Client(Userstatus userstatus, Gender gender, String fname, String lname, String email, String mobileno, String telephoneno, String addressno, String street1, String street2, String street3, Integer points, String image, Set<ClientHasRecoverquestion> clientHasRecoverquestions, Set<Comment> comments, Set<Watchlist> watchlists, Set<Userverificationcode> userverificationcodes, Set<Clientlogin> clientlogins, Set<Invoice> invoices, Set<Cart> carts) {
       this.userstatus = userstatus;
       this.gender = gender;
       this.fname = fname;
       this.lname = lname;
       this.email = email;
       this.mobileno = mobileno;
       this.telephoneno = telephoneno;
       this.addressno = addressno;
       this.street1 = street1;
       this.street2 = street2;
       this.street3 = street3;
       this.points = points;
       this.image = image;
       this.clientHasRecoverquestions = clientHasRecoverquestions;
       this.comments = comments;
       this.watchlists = watchlists;
       this.userverificationcodes = userverificationcodes;
       this.clientlogins = clientlogins;
       this.invoices = invoices;
       this.carts = carts;
    }
   
    public Integer getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(Integer idClient) {
        this.idClient = idClient;
    }
    public Userstatus getUserstatus() {
        return this.userstatus;
    }
    
    public void setUserstatus(Userstatus userstatus) {
        this.userstatus = userstatus;
    }
    public Gender getGender() {
        return this.gender;
    }
    
    public void setGender(Gender gender) {
        this.gender = gender;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMobileno() {
        return this.mobileno;
    }
    
    public void setMobileno(String mobileno) {
        this.mobileno = mobileno;
    }
    public String getTelephoneno() {
        return this.telephoneno;
    }
    
    public void setTelephoneno(String telephoneno) {
        this.telephoneno = telephoneno;
    }
    public String getAddressno() {
        return this.addressno;
    }
    
    public void setAddressno(String addressno) {
        this.addressno = addressno;
    }
    public String getStreet1() {
        return this.street1;
    }
    
    public void setStreet1(String street1) {
        this.street1 = street1;
    }
    public String getStreet2() {
        return this.street2;
    }
    
    public void setStreet2(String street2) {
        this.street2 = street2;
    }
    public String getStreet3() {
        return this.street3;
    }
    
    public void setStreet3(String street3) {
        this.street3 = street3;
    }
    public Integer getPoints() {
        return this.points;
    }
    
    public void setPoints(Integer points) {
        this.points = points;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Set<ClientHasRecoverquestion> getClientHasRecoverquestions() {
        return this.clientHasRecoverquestions;
    }
    
    public void setClientHasRecoverquestions(Set<ClientHasRecoverquestion> clientHasRecoverquestions) {
        this.clientHasRecoverquestions = clientHasRecoverquestions;
    }
    public Set<Comment> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }
    public Set<Watchlist> getWatchlists() {
        return this.watchlists;
    }
    
    public void setWatchlists(Set<Watchlist> watchlists) {
        this.watchlists = watchlists;
    }
    public Set<Userverificationcode> getUserverificationcodes() {
        return this.userverificationcodes;
    }
    
    public void setUserverificationcodes(Set<Userverificationcode> userverificationcodes) {
        this.userverificationcodes = userverificationcodes;
    }
    public Set<Clientlogin> getClientlogins() {
        return this.clientlogins;
    }
    
    public void setClientlogins(Set<Clientlogin> clientlogins) {
        this.clientlogins = clientlogins;
    }
    public Set<Invoice> getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set<Invoice> invoices) {
        this.invoices = invoices;
    }
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }




}


