package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Clientlogginsession generated by hbm2java
 */
public class Clientlogginsession  implements java.io.Serializable {


     private Integer idClientLogginSession;
     private Clientlogin clientlogin;
     private Date inTime;
     private Date outTime;
     private String ipaddress;

    public Clientlogginsession() {
    }

	
    public Clientlogginsession(Clientlogin clientlogin) {
        this.clientlogin = clientlogin;
    }
    public Clientlogginsession(Clientlogin clientlogin, Date inTime, Date outTime, String ipaddress) {
       this.clientlogin = clientlogin;
       this.inTime = inTime;
       this.outTime = outTime;
       this.ipaddress = ipaddress;
    }
   
    public Integer getIdClientLogginSession() {
        return this.idClientLogginSession;
    }
    
    public void setIdClientLogginSession(Integer idClientLogginSession) {
        this.idClientLogginSession = idClientLogginSession;
    }
    public Clientlogin getClientlogin() {
        return this.clientlogin;
    }
    
    public void setClientlogin(Clientlogin clientlogin) {
        this.clientlogin = clientlogin;
    }
    public Date getInTime() {
        return this.inTime;
    }
    
    public void setInTime(Date inTime) {
        this.inTime = inTime;
    }
    public Date getOutTime() {
        return this.outTime;
    }
    
    public void setOutTime(Date outTime) {
        this.outTime = outTime;
    }
    public String getIpaddress() {
        return this.ipaddress;
    }
    
    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress;
    }




}


