package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Clientlogin generated by hbm2java
 */
public class Clientlogin  implements java.io.Serializable {


     private Integer idClientLogin;
     private Client client;
     private Loginstatus loginstatus;
     private String username;
     private String password;
     private Set<Clientlogginsession> clientlogginsessions = new HashSet<Clientlogginsession>(0);

    public Clientlogin() {
    }

	
    public Clientlogin(Client client, Loginstatus loginstatus) {
        this.client = client;
        this.loginstatus = loginstatus;
    }
    public Clientlogin(Client client, Loginstatus loginstatus, String username, String password, Set<Clientlogginsession> clientlogginsessions) {
       this.client = client;
       this.loginstatus = loginstatus;
       this.username = username;
       this.password = password;
       this.clientlogginsessions = clientlogginsessions;
    }
   
    public Integer getIdClientLogin() {
        return this.idClientLogin;
    }
    
    public void setIdClientLogin(Integer idClientLogin) {
        this.idClientLogin = idClientLogin;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Loginstatus getLoginstatus() {
        return this.loginstatus;
    }
    
    public void setLoginstatus(Loginstatus loginstatus) {
        this.loginstatus = loginstatus;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<Clientlogginsession> getClientlogginsessions() {
        return this.clientlogginsessions;
    }
    
    public void setClientlogginsessions(Set<Clientlogginsession> clientlogginsessions) {
        this.clientlogginsessions = clientlogginsessions;
    }




}


