package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0



/**
 * Clientpointalgo generated by hbm2java
 */
public class Clientpointalgo  implements java.io.Serializable {


     private int idclientpointalgo;
     private String clientpointrange;
     private Integer points;

    public Clientpointalgo() {
    }

	
    public Clientpointalgo(int idclientpointalgo) {
        this.idclientpointalgo = idclientpointalgo;
    }
    public Clientpointalgo(int idclientpointalgo, String clientpointrange, Integer points) {
       this.idclientpointalgo = idclientpointalgo;
       this.clientpointrange = clientpointrange;
       this.points = points;
    }
   
    public int getIdclientpointalgo() {
        return this.idclientpointalgo;
    }
    
    public void setIdclientpointalgo(int idclientpointalgo) {
        this.idclientpointalgo = idclientpointalgo;
    }
    public String getClientpointrange() {
        return this.clientpointrange;
    }
    
    public void setClientpointrange(String clientpointrange) {
        this.clientpointrange = clientpointrange;
    }
    public Integer getPoints() {
        return this.points;
    }
    
    public void setPoints(Integer points) {
        this.points = points;
    }




}


