package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0



/**
 * Deliveryitem generated by hbm2java
 */
public class Deliveryitem  implements java.io.Serializable {


     private Integer idDeliveryItem;
     private Deliverynotice deliverynotice;
     private Deliverystatus deliverystatus;
     private InvoiceHasStock invoiceHasStock;
     private String no;
     private String street;
     private String city;
     private String district;
     private String country;
     private String postalCode;
     private String fname;
     private String lname;
     private String mobile;

    public Deliveryitem() {
    }

	
    public Deliveryitem(Deliverystatus deliverystatus, InvoiceHasStock invoiceHasStock) {
        this.deliverystatus = deliverystatus;
        this.invoiceHasStock = invoiceHasStock;
    }
    public Deliveryitem(Deliverynotice deliverynotice, Deliverystatus deliverystatus, InvoiceHasStock invoiceHasStock, String no, String street, String city, String district, String country, String postalCode, String fname, String lname, String mobile) {
       this.deliverynotice = deliverynotice;
       this.deliverystatus = deliverystatus;
       this.invoiceHasStock = invoiceHasStock;
       this.no = no;
       this.street = street;
       this.city = city;
       this.district = district;
       this.country = country;
       this.postalCode = postalCode;
       this.fname = fname;
       this.lname = lname;
       this.mobile = mobile;
    }
   
    public Integer getIdDeliveryItem() {
        return this.idDeliveryItem;
    }
    
    public void setIdDeliveryItem(Integer idDeliveryItem) {
        this.idDeliveryItem = idDeliveryItem;
    }
    public Deliverynotice getDeliverynotice() {
        return this.deliverynotice;
    }
    
    public void setDeliverynotice(Deliverynotice deliverynotice) {
        this.deliverynotice = deliverynotice;
    }
    public Deliverystatus getDeliverystatus() {
        return this.deliverystatus;
    }
    
    public void setDeliverystatus(Deliverystatus deliverystatus) {
        this.deliverystatus = deliverystatus;
    }
    public InvoiceHasStock getInvoiceHasStock() {
        return this.invoiceHasStock;
    }
    
    public void setInvoiceHasStock(InvoiceHasStock invoiceHasStock) {
        this.invoiceHasStock = invoiceHasStock;
    }
    public String getNo() {
        return this.no;
    }
    
    public void setNo(String no) {
        this.no = no;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }




}


