package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Deliverydistrict generated by hbm2java
 */
public class Deliverydistrict  implements java.io.Serializable {


     private Integer idDeliveryDistrict;
     private String district;
     private Integer timeDurationMaxDays;
     private Integer timeDurationMinDays;
     private Set<SupplierHasDeliverydistrict> supplierHasDeliverydistricts = new HashSet<SupplierHasDeliverydistrict>(0);

    public Deliverydistrict() {
    }

    public Deliverydistrict(String district, Integer timeDurationMaxDays, Integer timeDurationMinDays, Set<SupplierHasDeliverydistrict> supplierHasDeliverydistricts) {
       this.district = district;
       this.timeDurationMaxDays = timeDurationMaxDays;
       this.timeDurationMinDays = timeDurationMinDays;
       this.supplierHasDeliverydistricts = supplierHasDeliverydistricts;
    }
   
    public Integer getIdDeliveryDistrict() {
        return this.idDeliveryDistrict;
    }
    
    public void setIdDeliveryDistrict(Integer idDeliveryDistrict) {
        this.idDeliveryDistrict = idDeliveryDistrict;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public Integer getTimeDurationMaxDays() {
        return this.timeDurationMaxDays;
    }
    
    public void setTimeDurationMaxDays(Integer timeDurationMaxDays) {
        this.timeDurationMaxDays = timeDurationMaxDays;
    }
    public Integer getTimeDurationMinDays() {
        return this.timeDurationMinDays;
    }
    
    public void setTimeDurationMinDays(Integer timeDurationMinDays) {
        this.timeDurationMinDays = timeDurationMinDays;
    }
    public Set<SupplierHasDeliverydistrict> getSupplierHasDeliverydistricts() {
        return this.supplierHasDeliverydistricts;
    }
    
    public void setSupplierHasDeliverydistricts(Set<SupplierHasDeliverydistrict> supplierHasDeliverydistricts) {
        this.supplierHasDeliverydistricts = supplierHasDeliverydistricts;
    }




}


