package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Deliverynotice generated by hbm2java
 */
public class Deliverynotice  implements java.io.Serializable {


     private Integer idDeliveryNotice;
     private String description;
     private String deliveryNoticeimage;
     private Set<Deliveryitem> deliveryitems = new HashSet<Deliveryitem>(0);

    public Deliverynotice() {
    }

    public Deliverynotice(String description, String deliveryNoticeimage, Set<Deliveryitem> deliveryitems) {
       this.description = description;
       this.deliveryNoticeimage = deliveryNoticeimage;
       this.deliveryitems = deliveryitems;
    }
   
    public Integer getIdDeliveryNotice() {
        return this.idDeliveryNotice;
    }
    
    public void setIdDeliveryNotice(Integer idDeliveryNotice) {
        this.idDeliveryNotice = idDeliveryNotice;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getDeliveryNoticeimage() {
        return this.deliveryNoticeimage;
    }
    
    public void setDeliveryNoticeimage(String deliveryNoticeimage) {
        this.deliveryNoticeimage = deliveryNoticeimage;
    }
    public Set<Deliveryitem> getDeliveryitems() {
        return this.deliveryitems;
    }
    
    public void setDeliveryitems(Set<Deliveryitem> deliveryitems) {
        this.deliveryitems = deliveryitems;
    }




}


