package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Deliverystatus generated by hbm2java
 */
public class Deliverystatus  implements java.io.Serializable {


     private Integer idDeliveryStatus;
     private String deliveryStatus;
     private Set<Deliveryitem> deliveryitems = new HashSet<Deliveryitem>(0);

    public Deliverystatus() {
    }

    public Deliverystatus(String deliveryStatus, Set<Deliveryitem> deliveryitems) {
       this.deliveryStatus = deliveryStatus;
       this.deliveryitems = deliveryitems;
    }
   
    public Integer getIdDeliveryStatus() {
        return this.idDeliveryStatus;
    }
    
    public void setIdDeliveryStatus(Integer idDeliveryStatus) {
        this.idDeliveryStatus = idDeliveryStatus;
    }
    public String getDeliveryStatus() {
        return this.deliveryStatus;
    }
    
    public void setDeliveryStatus(String deliveryStatus) {
        this.deliveryStatus = deliveryStatus;
    }
    public Set<Deliveryitem> getDeliveryitems() {
        return this.deliveryitems;
    }
    
    public void setDeliveryitems(Set<Deliveryitem> deliveryitems) {
        this.deliveryitems = deliveryitems;
    }




}


