package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Gendertype generated by hbm2java
 */
public class Gendertype  implements java.io.Serializable {


     private Integer idGenderType;
     private String genderType;
     private Set<Product> products = new HashSet<Product>(0);

    public Gendertype() {
    }

    public Gendertype(String genderType, Set<Product> products) {
       this.genderType = genderType;
       this.products = products;
    }
   
    public Integer getIdGenderType() {
        return this.idGenderType;
    }
    
    public void setIdGenderType(Integer idGenderType) {
        this.idGenderType = idGenderType;
    }
    public String getGenderType() {
        return this.genderType;
    }
    
    public void setGenderType(String genderType) {
        this.genderType = genderType;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


