package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Grade generated by hbm2java
 */
public class Grade  implements java.io.Serializable {


     private Integer idGrade;
     private String grade;
     private Set<Product> products = new HashSet<Product>(0);

    public Grade() {
    }

    public Grade(String grade, Set<Product> products) {
       this.grade = grade;
       this.products = products;
    }
   
    public Integer getIdGrade() {
        return this.idGrade;
    }
    
    public void setIdGrade(Integer idGrade) {
        this.idGrade = idGrade;
    }
    public String getGrade() {
        return this.grade;
    }
    
    public void setGrade(String grade) {
        this.grade = grade;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


