package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Interfaces generated by hbm2java
 */
public class Interfaces  implements java.io.Serializable {


     private Integer idInterfaces;
     private String url;
     private String displayName;
     private Set<Supplierprivilages> supplierprivilageses = new HashSet<Supplierprivilages>(0);
     private Set<Adminprivilages> adminprivilageses = new HashSet<Adminprivilages>(0);
     private Set<Clientprivilages> clientprivilageses = new HashSet<Clientprivilages>(0);

    public Interfaces() {
    }

    public Interfaces(String url, String displayName, Set<Supplierprivilages> supplierprivilageses, Set<Adminprivilages> adminprivilageses, Set<Clientprivilages> clientprivilageses) {
       this.url = url;
       this.displayName = displayName;
       this.supplierprivilageses = supplierprivilageses;
       this.adminprivilageses = adminprivilageses;
       this.clientprivilageses = clientprivilageses;
    }
   
    public Integer getIdInterfaces() {
        return this.idInterfaces;
    }
    
    public void setIdInterfaces(Integer idInterfaces) {
        this.idInterfaces = idInterfaces;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public Set<Supplierprivilages> getSupplierprivilageses() {
        return this.supplierprivilageses;
    }
    
    public void setSupplierprivilageses(Set<Supplierprivilages> supplierprivilageses) {
        this.supplierprivilageses = supplierprivilageses;
    }
    public Set<Adminprivilages> getAdminprivilageses() {
        return this.adminprivilageses;
    }
    
    public void setAdminprivilageses(Set<Adminprivilages> adminprivilageses) {
        this.adminprivilageses = adminprivilageses;
    }
    public Set<Clientprivilages> getClientprivilageses() {
        return this.clientprivilageses;
    }
    
    public void setClientprivilageses(Set<Clientprivilages> clientprivilageses) {
        this.clientprivilageses = clientprivilageses;
    }




}


