package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer idInvoice;
     private Client client;
     private Date date;
     private Date time;
     private Double netTotal;
     private Set<InvoiceHasStock> invoiceHasStocks = new HashSet<InvoiceHasStock>(0);

    public Invoice() {
    }

	
    public Invoice(Client client) {
        this.client = client;
    }
    public Invoice(Client client, Date date, Date time, Double netTotal, Set<InvoiceHasStock> invoiceHasStocks) {
       this.client = client;
       this.date = date;
       this.time = time;
       this.netTotal = netTotal;
       this.invoiceHasStocks = invoiceHasStocks;
    }
   
    public Integer getIdInvoice() {
        return this.idInvoice;
    }
    
    public void setIdInvoice(Integer idInvoice) {
        this.idInvoice = idInvoice;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public Double getNetTotal() {
        return this.netTotal;
    }
    
    public void setNetTotal(Double netTotal) {
        this.netTotal = netTotal;
    }
    public Set<InvoiceHasStock> getInvoiceHasStocks() {
        return this.invoiceHasStocks;
    }
    
    public void setInvoiceHasStocks(Set<InvoiceHasStock> invoiceHasStocks) {
        this.invoiceHasStocks = invoiceHasStocks;
    }




}


