package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * InvoiceHasStock generated by hbm2java
 */
public class InvoiceHasStock  implements java.io.Serializable {


     private Integer invoiceHasStockid;
     private Stock stock;
     private Invoice invoice;
     private Double qty;
     private Double total;
     private Set<Deliveryitem> deliveryitems = new HashSet<Deliveryitem>(0);

    public InvoiceHasStock() {
    }

	
    public InvoiceHasStock(Stock stock, Invoice invoice) {
        this.stock = stock;
        this.invoice = invoice;
    }
    public InvoiceHasStock(Stock stock, Invoice invoice, Double qty, Double total, Set<Deliveryitem> deliveryitems) {
       this.stock = stock;
       this.invoice = invoice;
       this.qty = qty;
       this.total = total;
       this.deliveryitems = deliveryitems;
    }
   
    public Integer getInvoiceHasStockid() {
        return this.invoiceHasStockid;
    }
    
    public void setInvoiceHasStockid(Integer invoiceHasStockid) {
        this.invoiceHasStockid = invoiceHasStockid;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Set<Deliveryitem> getDeliveryitems() {
        return this.deliveryitems;
    }
    
    public void setDeliveryitems(Set<Deliveryitem> deliveryitems) {
        this.deliveryitems = deliveryitems;
    }




}


