package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Loginstatus generated by hbm2java
 */
public class Loginstatus  implements java.io.Serializable {


     private Integer idLoginStatus;
     private String loginStatus;
     private Set<Clientlogin> clientlogins = new HashSet<Clientlogin>(0);
     private Set<Adminlogin> adminlogins = new HashSet<Adminlogin>(0);
     private Set<Supplierlogin> supplierlogins = new HashSet<Supplierlogin>(0);

    public Loginstatus() {
    }

    public Loginstatus(String loginStatus, Set<Clientlogin> clientlogins, Set<Adminlogin> adminlogins, Set<Supplierlogin> supplierlogins) {
       this.loginStatus = loginStatus;
       this.clientlogins = clientlogins;
       this.adminlogins = adminlogins;
       this.supplierlogins = supplierlogins;
    }
   
    public Integer getIdLoginStatus() {
        return this.idLoginStatus;
    }
    
    public void setIdLoginStatus(Integer idLoginStatus) {
        this.idLoginStatus = idLoginStatus;
    }
    public String getLoginStatus() {
        return this.loginStatus;
    }
    
    public void setLoginStatus(String loginStatus) {
        this.loginStatus = loginStatus;
    }
    public Set<Clientlogin> getClientlogins() {
        return this.clientlogins;
    }
    
    public void setClientlogins(Set<Clientlogin> clientlogins) {
        this.clientlogins = clientlogins;
    }
    public Set<Adminlogin> getAdminlogins() {
        return this.adminlogins;
    }
    
    public void setAdminlogins(Set<Adminlogin> adminlogins) {
        this.adminlogins = adminlogins;
    }
    public Set<Supplierlogin> getSupplierlogins() {
        return this.supplierlogins;
    }
    
    public void setSupplierlogins(Set<Supplierlogin> supplierlogins) {
        this.supplierlogins = supplierlogins;
    }




}


