package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0



/**
 * Mainaccount generated by hbm2java
 */
public class Mainaccount  implements java.io.Serializable {


     private Integer idMainAccount;
     private Double mainAccount;

    public Mainaccount() {
    }

    public Mainaccount(Double mainAccount) {
       this.mainAccount = mainAccount;
    }
   
    public Integer getIdMainAccount() {
        return this.idMainAccount;
    }
    
    public void setIdMainAccount(Integer idMainAccount) {
        this.idMainAccount = idMainAccount;
    }
    public Double getMainAccount() {
        return this.mainAccount;
    }
    
    public void setMainAccount(Double mainAccount) {
        this.mainAccount = mainAccount;
    }




}


