package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Movement generated by hbm2java
 */
public class Movement  implements java.io.Serializable {


     private Integer idmovement;
     private String movement;
     private Set<Product> products = new HashSet<Product>(0);

    public Movement() {
    }

    public Movement(String movement, Set<Product> products) {
       this.movement = movement;
       this.products = products;
    }
   
    public Integer getIdmovement() {
        return this.idmovement;
    }
    
    public void setIdmovement(Integer idmovement) {
        this.idmovement = idmovement;
    }
    public String getMovement() {
        return this.movement;
    }
    
    public void setMovement(String movement) {
        this.movement = movement;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


