package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Posttype generated by hbm2java
 */
public class Posttype  implements java.io.Serializable {


     private Integer idPostType;
     private String postType;
     private String description;
     private Set<Supplier> suppliers = new HashSet<Supplier>(0);

    public Posttype() {
    }

    public Posttype(String postType, String description, Set<Supplier> suppliers) {
       this.postType = postType;
       this.description = description;
       this.suppliers = suppliers;
    }
   
    public Integer getIdPostType() {
        return this.idPostType;
    }
    
    public void setIdPostType(Integer idPostType) {
        this.idPostType = idPostType;
    }
    public String getPostType() {
        return this.postType;
    }
    
    public void setPostType(String postType) {
        this.postType = postType;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<Supplier> getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Set<Supplier> suppliers) {
        this.suppliers = suppliers;
    }




}


