package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0



/**
 * ProductHasSubcategories generated by hbm2java
 */
public class ProductHasSubcategories  implements java.io.Serializable {


     private Integer idProductHasSubCategories;
     private Subcategories subcategories;
     private Product product;

    public ProductHasSubcategories() {
    }

    public ProductHasSubcategories(Subcategories subcategories, Product product) {
       this.subcategories = subcategories;
       this.product = product;
    }
   
    public Integer getIdProductHasSubCategories() {
        return this.idProductHasSubCategories;
    }
    
    public void setIdProductHasSubCategories(Integer idProductHasSubCategories) {
        this.idProductHasSubCategories = idProductHasSubCategories;
    }
    public Subcategories getSubcategories() {
        return this.subcategories;
    }
    
    public void setSubcategories(Subcategories subcategories) {
        this.subcategories = subcategories;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }




}


