package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Productstatus generated by hbm2java
 */
public class Productstatus  implements java.io.Serializable {


     private Integer idProductStatus;
     private String productStatus;
     private Set<Product> products = new HashSet<Product>(0);

    public Productstatus() {
    }

    public Productstatus(String productStatus, Set<Product> products) {
       this.productStatus = productStatus;
       this.products = products;
    }
   
    public Integer getIdProductStatus() {
        return this.idProductStatus;
    }
    
    public void setIdProductStatus(Integer idProductStatus) {
        this.idProductStatus = idProductStatus;
    }
    public String getProductStatus() {
        return this.productStatus;
    }
    
    public void setProductStatus(String productStatus) {
        this.productStatus = productStatus;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


