package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer idProduct;
     private Agelimit agelimit;
     private Brand brand;
     private Gendertype gendertype;
     private Strapcolor strapcolor;
     private Productstatus productstatus;
     private Maincolor maincolor;
     private Weight weight;
     private Casesize casesize;
     private Grade grade;
     private Straptype straptype;
     private Watchshape watchshape;
     private Dialcolor dialcolor;
     private Analogdigital analogdigital;
     private Casetype casetype;
     private Movement movement;
     private Packaging packaging;
     private Waterresistency waterresistency;
     private String productName;
     private String searchWord;
     private Double minQty;
     private String itemCode;
     private String image;
     private String image1;
     private String image2;
     private Set<Stock> stocks = new HashSet<Stock>(0);
     private Set<ProductHasSubcategories> productHasSubcategorieses = new HashSet<ProductHasSubcategories>(0);

    public Product() {
    }

	
    public Product(Agelimit agelimit, Brand brand, Gendertype gendertype, Strapcolor strapcolor, Productstatus productstatus, Maincolor maincolor, Weight weight, Casesize casesize, Grade grade, Straptype straptype, Watchshape watchshape, Dialcolor dialcolor, Analogdigital analogdigital, Casetype casetype, Movement movement, Packaging packaging, Waterresistency waterresistency) {
        this.agelimit = agelimit;
        this.brand = brand;
        this.gendertype = gendertype;
        this.strapcolor = strapcolor;
        this.productstatus = productstatus;
        this.maincolor = maincolor;
        this.weight = weight;
        this.casesize = casesize;
        this.grade = grade;
        this.straptype = straptype;
        this.watchshape = watchshape;
        this.dialcolor = dialcolor;
        this.analogdigital = analogdigital;
        this.casetype = casetype;
        this.movement = movement;
        this.packaging = packaging;
        this.waterresistency = waterresistency;
    }
    public Product(Agelimit agelimit, Brand brand, Gendertype gendertype, Strapcolor strapcolor, Productstatus productstatus, Maincolor maincolor, Weight weight, Casesize casesize, Grade grade, Straptype straptype, Watchshape watchshape, Dialcolor dialcolor, Analogdigital analogdigital, Casetype casetype, Movement movement, Packaging packaging, Waterresistency waterresistency, String productName, String searchWord, Double minQty, String itemCode, String image, String image1, String image2, Set<Stock> stocks, Set<ProductHasSubcategories> productHasSubcategorieses) {
       this.agelimit = agelimit;
       this.brand = brand;
       this.gendertype = gendertype;
       this.strapcolor = strapcolor;
       this.productstatus = productstatus;
       this.maincolor = maincolor;
       this.weight = weight;
       this.casesize = casesize;
       this.grade = grade;
       this.straptype = straptype;
       this.watchshape = watchshape;
       this.dialcolor = dialcolor;
       this.analogdigital = analogdigital;
       this.casetype = casetype;
       this.movement = movement;
       this.packaging = packaging;
       this.waterresistency = waterresistency;
       this.productName = productName;
       this.searchWord = searchWord;
       this.minQty = minQty;
       this.itemCode = itemCode;
       this.image = image;
       this.image1 = image1;
       this.image2 = image2;
       this.stocks = stocks;
       this.productHasSubcategorieses = productHasSubcategorieses;
    }
   
    public Integer getIdProduct() {
        return this.idProduct;
    }
    
    public void setIdProduct(Integer idProduct) {
        this.idProduct = idProduct;
    }
    public Agelimit getAgelimit() {
        return this.agelimit;
    }
    
    public void setAgelimit(Agelimit agelimit) {
        this.agelimit = agelimit;
    }
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }
    public Gendertype getGendertype() {
        return this.gendertype;
    }
    
    public void setGendertype(Gendertype gendertype) {
        this.gendertype = gendertype;
    }
    public Strapcolor getStrapcolor() {
        return this.strapcolor;
    }
    
    public void setStrapcolor(Strapcolor strapcolor) {
        this.strapcolor = strapcolor;
    }
    public Productstatus getProductstatus() {
        return this.productstatus;
    }
    
    public void setProductstatus(Productstatus productstatus) {
        this.productstatus = productstatus;
    }
    public Maincolor getMaincolor() {
        return this.maincolor;
    }
    
    public void setMaincolor(Maincolor maincolor) {
        this.maincolor = maincolor;
    }
    public Weight getWeight() {
        return this.weight;
    }
    
    public void setWeight(Weight weight) {
        this.weight = weight;
    }
    public Casesize getCasesize() {
        return this.casesize;
    }
    
    public void setCasesize(Casesize casesize) {
        this.casesize = casesize;
    }
    public Grade getGrade() {
        return this.grade;
    }
    
    public void setGrade(Grade grade) {
        this.grade = grade;
    }
    public Straptype getStraptype() {
        return this.straptype;
    }
    
    public void setStraptype(Straptype straptype) {
        this.straptype = straptype;
    }
    public Watchshape getWatchshape() {
        return this.watchshape;
    }
    
    public void setWatchshape(Watchshape watchshape) {
        this.watchshape = watchshape;
    }
    public Dialcolor getDialcolor() {
        return this.dialcolor;
    }
    
    public void setDialcolor(Dialcolor dialcolor) {
        this.dialcolor = dialcolor;
    }
    public Analogdigital getAnalogdigital() {
        return this.analogdigital;
    }
    
    public void setAnalogdigital(Analogdigital analogdigital) {
        this.analogdigital = analogdigital;
    }
    public Casetype getCasetype() {
        return this.casetype;
    }
    
    public void setCasetype(Casetype casetype) {
        this.casetype = casetype;
    }
    public Movement getMovement() {
        return this.movement;
    }
    
    public void setMovement(Movement movement) {
        this.movement = movement;
    }
    public Packaging getPackaging() {
        return this.packaging;
    }
    
    public void setPackaging(Packaging packaging) {
        this.packaging = packaging;
    }
    public Waterresistency getWaterresistency() {
        return this.waterresistency;
    }
    
    public void setWaterresistency(Waterresistency waterresistency) {
        this.waterresistency = waterresistency;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getSearchWord() {
        return this.searchWord;
    }
    
    public void setSearchWord(String searchWord) {
        this.searchWord = searchWord;
    }
    public Double getMinQty() {
        return this.minQty;
    }
    
    public void setMinQty(Double minQty) {
        this.minQty = minQty;
    }
    public String getItemCode() {
        return this.itemCode;
    }
    
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getImage1() {
        return this.image1;
    }
    
    public void setImage1(String image1) {
        this.image1 = image1;
    }
    public String getImage2() {
        return this.image2;
    }
    
    public void setImage2(String image2) {
        this.image2 = image2;
    }
    public Set<Stock> getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set<Stock> stocks) {
        this.stocks = stocks;
    }
    public Set<ProductHasSubcategories> getProductHasSubcategorieses() {
        return this.productHasSubcategorieses;
    }
    
    public void setProductHasSubcategorieses(Set<ProductHasSubcategories> productHasSubcategorieses) {
        this.productHasSubcategorieses = productHasSubcategorieses;
    }




}


