package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Profit generated by hbm2java
 */
public class Profit  implements java.io.Serializable {


     private Integer idProfit;
     private Double profit;
     private Date date;

    public Profit() {
    }

    public Profit(Double profit, Date date) {
       this.profit = profit;
       this.date = date;
    }
   
    public Integer getIdProfit() {
        return this.idProfit;
    }
    
    public void setIdProfit(Integer idProfit) {
        this.idProfit = idProfit;
    }
    public Double getProfit() {
        return this.profit;
    }
    
    public void setProfit(Double profit) {
        this.profit = profit;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


