package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Recoverquestion generated by hbm2java
 */
public class Recoverquestion  implements java.io.Serializable {


     private Integer idRecoverQuestion;
     private Recoverquestionstatus recoverquestionstatus;
     private String recoverQuestion;
     private Set<ClientHasRecoverquestion> clientHasRecoverquestions = new HashSet<ClientHasRecoverquestion>(0);
     private Set<SupplierHasRecoverquestion> supplierHasRecoverquestions = new HashSet<SupplierHasRecoverquestion>(0);

    public Recoverquestion() {
    }

	
    public Recoverquestion(Recoverquestionstatus recoverquestionstatus) {
        this.recoverquestionstatus = recoverquestionstatus;
    }
    public Recoverquestion(Recoverquestionstatus recoverquestionstatus, String recoverQuestion, Set<ClientHasRecoverquestion> clientHasRecoverquestions, Set<SupplierHasRecoverquestion> supplierHasRecoverquestions) {
       this.recoverquestionstatus = recoverquestionstatus;
       this.recoverQuestion = recoverQuestion;
       this.clientHasRecoverquestions = clientHasRecoverquestions;
       this.supplierHasRecoverquestions = supplierHasRecoverquestions;
    }
   
    public Integer getIdRecoverQuestion() {
        return this.idRecoverQuestion;
    }
    
    public void setIdRecoverQuestion(Integer idRecoverQuestion) {
        this.idRecoverQuestion = idRecoverQuestion;
    }
    public Recoverquestionstatus getRecoverquestionstatus() {
        return this.recoverquestionstatus;
    }
    
    public void setRecoverquestionstatus(Recoverquestionstatus recoverquestionstatus) {
        this.recoverquestionstatus = recoverquestionstatus;
    }
    public String getRecoverQuestion() {
        return this.recoverQuestion;
    }
    
    public void setRecoverQuestion(String recoverQuestion) {
        this.recoverQuestion = recoverQuestion;
    }
    public Set<ClientHasRecoverquestion> getClientHasRecoverquestions() {
        return this.clientHasRecoverquestions;
    }
    
    public void setClientHasRecoverquestions(Set<ClientHasRecoverquestion> clientHasRecoverquestions) {
        this.clientHasRecoverquestions = clientHasRecoverquestions;
    }
    public Set<SupplierHasRecoverquestion> getSupplierHasRecoverquestions() {
        return this.supplierHasRecoverquestions;
    }
    
    public void setSupplierHasRecoverquestions(Set<SupplierHasRecoverquestion> supplierHasRecoverquestions) {
        this.supplierHasRecoverquestions = supplierHasRecoverquestions;
    }




}


