package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Recoverquestionstatus generated by hbm2java
 */
public class Recoverquestionstatus  implements java.io.Serializable {


     private Integer idRecoverQuestionStatus;
     private String recoverQuestionStatus;
     private Set<Recoverquestion> recoverquestions = new HashSet<Recoverquestion>(0);

    public Recoverquestionstatus() {
    }

    public Recoverquestionstatus(String recoverQuestionStatus, Set<Recoverquestion> recoverquestions) {
       this.recoverQuestionStatus = recoverQuestionStatus;
       this.recoverquestions = recoverquestions;
    }
   
    public Integer getIdRecoverQuestionStatus() {
        return this.idRecoverQuestionStatus;
    }
    
    public void setIdRecoverQuestionStatus(Integer idRecoverQuestionStatus) {
        this.idRecoverQuestionStatus = idRecoverQuestionStatus;
    }
    public String getRecoverQuestionStatus() {
        return this.recoverQuestionStatus;
    }
    
    public void setRecoverQuestionStatus(String recoverQuestionStatus) {
        this.recoverQuestionStatus = recoverQuestionStatus;
    }
    public Set<Recoverquestion> getRecoverquestions() {
        return this.recoverquestions;
    }
    
    public void setRecoverquestions(Set<Recoverquestion> recoverquestions) {
        this.recoverquestions = recoverquestions;
    }




}


