package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0



/**
 * Sitedetails generated by hbm2java
 */
public class Sitedetails  implements java.io.Serializable {


     private Integer idSiteDetails;
     private String siteName;
     private String email;
     private String no;
     private String street;
     private String city;
     private String postalcode;
     private String country;
     private String logo;

    public Sitedetails() {
    }

    public Sitedetails(String siteName, String email, String no, String street, String city, String postalcode, String country, String logo) {
       this.siteName = siteName;
       this.email = email;
       this.no = no;
       this.street = street;
       this.city = city;
       this.postalcode = postalcode;
       this.country = country;
       this.logo = logo;
    }
   
    public Integer getIdSiteDetails() {
        return this.idSiteDetails;
    }
    
    public void setIdSiteDetails(Integer idSiteDetails) {
        this.idSiteDetails = idSiteDetails;
    }
    public String getSiteName() {
        return this.siteName;
    }
    
    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNo() {
        return this.no;
    }
    
    public void setNo(String no) {
        this.no = no;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getPostalcode() {
        return this.postalcode;
    }
    
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }




}


