package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0



/**
 * Sliderdetails generated by hbm2java
 */
public class Sliderdetails  implements java.io.Serializable {


     private Integer idSliderDetails;
     private String sliderImage1;
     private String sliderImage2;
     private String sliderImage3;
     private String sliderImage4;
     private String sliderHeader1;
     private String sliderHeader2;
     private String sliderHeader3;
     private String sliderHeader4;
     private String sliderText1;
     private String sliderText2;
     private String sliderText3;
     private String sliderText4;

    public Sliderdetails() {
    }

    public Sliderdetails(String sliderImage1, String sliderImage2, String sliderImage3, String sliderImage4, String sliderHeader1, String sliderHeader2, String sliderHeader3, String sliderHeader4, String sliderText1, String sliderText2, String sliderText3, String sliderText4) {
       this.sliderImage1 = sliderImage1;
       this.sliderImage2 = sliderImage2;
       this.sliderImage3 = sliderImage3;
       this.sliderImage4 = sliderImage4;
       this.sliderHeader1 = sliderHeader1;
       this.sliderHeader2 = sliderHeader2;
       this.sliderHeader3 = sliderHeader3;
       this.sliderHeader4 = sliderHeader4;
       this.sliderText1 = sliderText1;
       this.sliderText2 = sliderText2;
       this.sliderText3 = sliderText3;
       this.sliderText4 = sliderText4;
    }
   
    public Integer getIdSliderDetails() {
        return this.idSliderDetails;
    }
    
    public void setIdSliderDetails(Integer idSliderDetails) {
        this.idSliderDetails = idSliderDetails;
    }
    public String getSliderImage1() {
        return this.sliderImage1;
    }
    
    public void setSliderImage1(String sliderImage1) {
        this.sliderImage1 = sliderImage1;
    }
    public String getSliderImage2() {
        return this.sliderImage2;
    }
    
    public void setSliderImage2(String sliderImage2) {
        this.sliderImage2 = sliderImage2;
    }
    public String getSliderImage3() {
        return this.sliderImage3;
    }
    
    public void setSliderImage3(String sliderImage3) {
        this.sliderImage3 = sliderImage3;
    }
    public String getSliderImage4() {
        return this.sliderImage4;
    }
    
    public void setSliderImage4(String sliderImage4) {
        this.sliderImage4 = sliderImage4;
    }
    public String getSliderHeader1() {
        return this.sliderHeader1;
    }
    
    public void setSliderHeader1(String sliderHeader1) {
        this.sliderHeader1 = sliderHeader1;
    }
    public String getSliderHeader2() {
        return this.sliderHeader2;
    }
    
    public void setSliderHeader2(String sliderHeader2) {
        this.sliderHeader2 = sliderHeader2;
    }
    public String getSliderHeader3() {
        return this.sliderHeader3;
    }
    
    public void setSliderHeader3(String sliderHeader3) {
        this.sliderHeader3 = sliderHeader3;
    }
    public String getSliderHeader4() {
        return this.sliderHeader4;
    }
    
    public void setSliderHeader4(String sliderHeader4) {
        this.sliderHeader4 = sliderHeader4;
    }
    public String getSliderText1() {
        return this.sliderText1;
    }
    
    public void setSliderText1(String sliderText1) {
        this.sliderText1 = sliderText1;
    }
    public String getSliderText2() {
        return this.sliderText2;
    }
    
    public void setSliderText2(String sliderText2) {
        this.sliderText2 = sliderText2;
    }
    public String getSliderText3() {
        return this.sliderText3;
    }
    
    public void setSliderText3(String sliderText3) {
        this.sliderText3 = sliderText3;
    }
    public String getSliderText4() {
        return this.sliderText4;
    }
    
    public void setSliderText4(String sliderText4) {
        this.sliderText4 = sliderText4;
    }




}


