package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Stock generated by hbm2java
 */
public class Stock  implements java.io.Serializable {


     private Integer idStock;
     private Supplier supplier;
     private Product product;
     private Double qty;
     private Double sellingPrice;
     private String barcode;
     private Double finalPrice;
     private Double discount;
     private Set<Watchlist> watchlists = new HashSet<Watchlist>(0);
     private Set<CartHasStock> cartHasStocks = new HashSet<CartHasStock>(0);
     private Set<SupplierHasStock> supplierHasStocks = new HashSet<SupplierHasStock>(0);
     private Set<Comment> comments = new HashSet<Comment>(0);
     private Set<InvoiceHasStock> invoiceHasStocks = new HashSet<InvoiceHasStock>(0);
     private Set<SupplierHasDeliverydistrictHasStock> supplierHasDeliverydistrictHasStocks = new HashSet<SupplierHasDeliverydistrictHasStock>(0);

    public Stock() {
    }

	
    public Stock(Supplier supplier, Product product) {
        this.supplier = supplier;
        this.product = product;
    }
    public Stock(Supplier supplier, Product product, Double qty, Double sellingPrice, String barcode, Double finalPrice, Double discount, Set<Watchlist> watchlists, Set<CartHasStock> cartHasStocks, Set<SupplierHasStock> supplierHasStocks, Set<Comment> comments, Set<InvoiceHasStock> invoiceHasStocks, Set<SupplierHasDeliverydistrictHasStock> supplierHasDeliverydistrictHasStocks) {
       this.supplier = supplier;
       this.product = product;
       this.qty = qty;
       this.sellingPrice = sellingPrice;
       this.barcode = barcode;
       this.finalPrice = finalPrice;
       this.discount = discount;
       this.watchlists = watchlists;
       this.cartHasStocks = cartHasStocks;
       this.supplierHasStocks = supplierHasStocks;
       this.comments = comments;
       this.invoiceHasStocks = invoiceHasStocks;
       this.supplierHasDeliverydistrictHasStocks = supplierHasDeliverydistrictHasStocks;
    }
   
    public Integer getIdStock() {
        return this.idStock;
    }
    
    public void setIdStock(Integer idStock) {
        this.idStock = idStock;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public Double getSellingPrice() {
        return this.sellingPrice;
    }
    
    public void setSellingPrice(Double sellingPrice) {
        this.sellingPrice = sellingPrice;
    }
    public String getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }
    public Double getFinalPrice() {
        return this.finalPrice;
    }
    
    public void setFinalPrice(Double finalPrice) {
        this.finalPrice = finalPrice;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Set<Watchlist> getWatchlists() {
        return this.watchlists;
    }
    
    public void setWatchlists(Set<Watchlist> watchlists) {
        this.watchlists = watchlists;
    }
    public Set<CartHasStock> getCartHasStocks() {
        return this.cartHasStocks;
    }
    
    public void setCartHasStocks(Set<CartHasStock> cartHasStocks) {
        this.cartHasStocks = cartHasStocks;
    }
    public Set<SupplierHasStock> getSupplierHasStocks() {
        return this.supplierHasStocks;
    }
    
    public void setSupplierHasStocks(Set<SupplierHasStock> supplierHasStocks) {
        this.supplierHasStocks = supplierHasStocks;
    }
    public Set<Comment> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }
    public Set<InvoiceHasStock> getInvoiceHasStocks() {
        return this.invoiceHasStocks;
    }
    
    public void setInvoiceHasStocks(Set<InvoiceHasStock> invoiceHasStocks) {
        this.invoiceHasStocks = invoiceHasStocks;
    }
    public Set<SupplierHasDeliverydistrictHasStock> getSupplierHasDeliverydistrictHasStocks() {
        return this.supplierHasDeliverydistrictHasStocks;
    }
    
    public void setSupplierHasDeliverydistrictHasStocks(Set<SupplierHasDeliverydistrictHasStock> supplierHasDeliverydistrictHasStocks) {
        this.supplierHasDeliverydistrictHasStocks = supplierHasDeliverydistrictHasStocks;
    }




}


