package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Straptype generated by hbm2java
 */
public class Straptype  implements java.io.Serializable {


     private Integer idStrapType;
     private String strapType;
     private Set<Product> products = new HashSet<Product>(0);

    public Straptype() {
    }

    public Straptype(String strapType, Set<Product> products) {
       this.strapType = strapType;
       this.products = products;
    }
   
    public Integer getIdStrapType() {
        return this.idStrapType;
    }
    
    public void setIdStrapType(Integer idStrapType) {
        this.idStrapType = idStrapType;
    }
    public String getStrapType() {
        return this.strapType;
    }
    
    public void setStrapType(String strapType) {
        this.strapType = strapType;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


