package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Strapcolor generated by hbm2java
 */
public class Strapcolor  implements java.io.Serializable {


     private Integer idStrapColor;
     private String strapColor;
     private Set<Product> products = new HashSet<Product>(0);

    public Strapcolor() {
    }

    public Strapcolor(String strapColor, Set<Product> products) {
       this.strapColor = strapColor;
       this.products = products;
    }
   
    public Integer getIdStrapColor() {
        return this.idStrapColor;
    }
    
    public void setIdStrapColor(Integer idStrapColor) {
        this.idStrapColor = idStrapColor;
    }
    public String getStrapColor() {
        return this.strapColor;
    }
    
    public void setStrapColor(String strapColor) {
        this.strapColor = strapColor;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


