package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Subcategories generated by hbm2java
 */
public class Subcategories  implements java.io.Serializable {


     private Integer idSubCategories;
     private String subCategories;
     private Set<ProductHasSubcategories> productHasSubcategorieses = new HashSet<ProductHasSubcategories>(0);

    public Subcategories() {
    }

    public Subcategories(String subCategories, Set<ProductHasSubcategories> productHasSubcategorieses) {
       this.subCategories = subCategories;
       this.productHasSubcategorieses = productHasSubcategorieses;
    }
   
    public Integer getIdSubCategories() {
        return this.idSubCategories;
    }
    
    public void setIdSubCategories(Integer idSubCategories) {
        this.idSubCategories = idSubCategories;
    }
    public String getSubCategories() {
        return this.subCategories;
    }
    
    public void setSubCategories(String subCategories) {
        this.subCategories = subCategories;
    }
    public Set<ProductHasSubcategories> getProductHasSubcategorieses() {
        return this.productHasSubcategorieses;
    }
    
    public void setProductHasSubcategorieses(Set<ProductHasSubcategories> productHasSubcategorieses) {
        this.productHasSubcategorieses = productHasSubcategorieses;
    }




}


