package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0



/**
 * Supplierprivilages generated by hbm2java
 */
public class Supplierprivilages  implements java.io.Serializable {


     private Integer idSupplierPrivilages;
     private Interfaces interfaces;

    public Supplierprivilages() {
    }

    public Supplierprivilages(Interfaces interfaces) {
       this.interfaces = interfaces;
    }
   
    public Integer getIdSupplierPrivilages() {
        return this.idSupplierPrivilages;
    }
    
    public void setIdSupplierPrivilages(Integer idSupplierPrivilages) {
        this.idSupplierPrivilages = idSupplierPrivilages;
    }
    public Interfaces getInterfaces() {
        return this.interfaces;
    }
    
    public void setInterfaces(Interfaces interfaces) {
        this.interfaces = interfaces;
    }




}


