package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Supplierloggingsession generated by hbm2java
 */
public class Supplierloggingsession  implements java.io.Serializable {


     private Integer idSupplierLoggingSession;
     private Supplierlogin supplierlogin;
     private Date inTime;
     private Date outTime;
     private String ipaddress;

    public Supplierloggingsession() {
    }

	
    public Supplierloggingsession(Supplierlogin supplierlogin) {
        this.supplierlogin = supplierlogin;
    }
    public Supplierloggingsession(Supplierlogin supplierlogin, Date inTime, Date outTime, String ipaddress) {
       this.supplierlogin = supplierlogin;
       this.inTime = inTime;
       this.outTime = outTime;
       this.ipaddress = ipaddress;
    }
   
    public Integer getIdSupplierLoggingSession() {
        return this.idSupplierLoggingSession;
    }
    
    public void setIdSupplierLoggingSession(Integer idSupplierLoggingSession) {
        this.idSupplierLoggingSession = idSupplierLoggingSession;
    }
    public Supplierlogin getSupplierlogin() {
        return this.supplierlogin;
    }
    
    public void setSupplierlogin(Supplierlogin supplierlogin) {
        this.supplierlogin = supplierlogin;
    }
    public Date getInTime() {
        return this.inTime;
    }
    
    public void setInTime(Date inTime) {
        this.inTime = inTime;
    }
    public Date getOutTime() {
        return this.outTime;
    }
    
    public void setOutTime(Date outTime) {
        this.outTime = outTime;
    }
    public String getIpaddress() {
        return this.ipaddress;
    }
    
    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress;
    }




}


