package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Supplierpayment generated by hbm2java
 */
public class Supplierpayment  implements java.io.Serializable {


     private Integer idSupplierPayment;
     private Supplier supplier;
     private Double supplierPayment;
     private Date date;
     private String depositImage;

    public Supplierpayment() {
    }

	
    public Supplierpayment(Supplier supplier) {
        this.supplier = supplier;
    }
    public Supplierpayment(Supplier supplier, Double supplierPayment, Date date, String depositImage) {
       this.supplier = supplier;
       this.supplierPayment = supplierPayment;
       this.date = date;
       this.depositImage = depositImage;
    }
   
    public Integer getIdSupplierPayment() {
        return this.idSupplierPayment;
    }
    
    public void setIdSupplierPayment(Integer idSupplierPayment) {
        this.idSupplierPayment = idSupplierPayment;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public Double getSupplierPayment() {
        return this.supplierPayment;
    }
    
    public void setSupplierPayment(Double supplierPayment) {
        this.supplierPayment = supplierPayment;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getDepositImage() {
        return this.depositImage;
    }
    
    public void setDepositImage(String depositImage) {
        this.depositImage = depositImage;
    }




}


