package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Supplier generated by hbm2java
 */
public class Supplier  implements java.io.Serializable {


     private Integer idSupplier;
     private Posttype posttype;
     private Userstatus userstatus;
     private String companyName;
     private String govRegistrationCode;
     private String mobileno;
     private String telephoneno;
     private String addressno;
     private String street1;
     private String street2;
     private String street3;
     private String email;
     private Integer points;
     private String supplierlogo;
     private Set<Stock> stocks = new HashSet<Stock>(0);
     private Set<SupplierHasStock> supplierHasStocks = new HashSet<SupplierHasStock>(0);
     private Set<Supplierverificationcode> supplierverificationcodes = new HashSet<Supplierverificationcode>(0);
     private Set<SupplierHasDeliverydistrict> supplierHasDeliverydistricts = new HashSet<SupplierHasDeliverydistrict>(0);
     private Set<Supplierlogin> supplierlogins = new HashSet<Supplierlogin>(0);
     private Set<Supplierpayment> supplierpayments = new HashSet<Supplierpayment>(0);
     private Set<SupplierHasRecoverquestion> supplierHasRecoverquestions = new HashSet<SupplierHasRecoverquestion>(0);

    public Supplier() {
    }

	
    public Supplier(Userstatus userstatus) {
        this.userstatus = userstatus;
    }
    public Supplier(Posttype posttype, Userstatus userstatus, String companyName, String govRegistrationCode, String mobileno, String telephoneno, String addressno, String street1, String street2, String street3, String email, Integer points, String supplierlogo, Set<Stock> stocks, Set<SupplierHasStock> supplierHasStocks, Set<Supplierverificationcode> supplierverificationcodes, Set<SupplierHasDeliverydistrict> supplierHasDeliverydistricts, Set<Supplierlogin> supplierlogins, Set<Supplierpayment> supplierpayments, Set<SupplierHasRecoverquestion> supplierHasRecoverquestions) {
       this.posttype = posttype;
       this.userstatus = userstatus;
       this.companyName = companyName;
       this.govRegistrationCode = govRegistrationCode;
       this.mobileno = mobileno;
       this.telephoneno = telephoneno;
       this.addressno = addressno;
       this.street1 = street1;
       this.street2 = street2;
       this.street3 = street3;
       this.email = email;
       this.points = points;
       this.supplierlogo = supplierlogo;
       this.stocks = stocks;
       this.supplierHasStocks = supplierHasStocks;
       this.supplierverificationcodes = supplierverificationcodes;
       this.supplierHasDeliverydistricts = supplierHasDeliverydistricts;
       this.supplierlogins = supplierlogins;
       this.supplierpayments = supplierpayments;
       this.supplierHasRecoverquestions = supplierHasRecoverquestions;
    }
   
    public Integer getIdSupplier() {
        return this.idSupplier;
    }
    
    public void setIdSupplier(Integer idSupplier) {
        this.idSupplier = idSupplier;
    }
    public Posttype getPosttype() {
        return this.posttype;
    }
    
    public void setPosttype(Posttype posttype) {
        this.posttype = posttype;
    }
    public Userstatus getUserstatus() {
        return this.userstatus;
    }
    
    public void setUserstatus(Userstatus userstatus) {
        this.userstatus = userstatus;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getGovRegistrationCode() {
        return this.govRegistrationCode;
    }
    
    public void setGovRegistrationCode(String govRegistrationCode) {
        this.govRegistrationCode = govRegistrationCode;
    }
    public String getMobileno() {
        return this.mobileno;
    }
    
    public void setMobileno(String mobileno) {
        this.mobileno = mobileno;
    }
    public String getTelephoneno() {
        return this.telephoneno;
    }
    
    public void setTelephoneno(String telephoneno) {
        this.telephoneno = telephoneno;
    }
    public String getAddressno() {
        return this.addressno;
    }
    
    public void setAddressno(String addressno) {
        this.addressno = addressno;
    }
    public String getStreet1() {
        return this.street1;
    }
    
    public void setStreet1(String street1) {
        this.street1 = street1;
    }
    public String getStreet2() {
        return this.street2;
    }
    
    public void setStreet2(String street2) {
        this.street2 = street2;
    }
    public String getStreet3() {
        return this.street3;
    }
    
    public void setStreet3(String street3) {
        this.street3 = street3;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getPoints() {
        return this.points;
    }
    
    public void setPoints(Integer points) {
        this.points = points;
    }
    public String getSupplierlogo() {
        return this.supplierlogo;
    }
    
    public void setSupplierlogo(String supplierlogo) {
        this.supplierlogo = supplierlogo;
    }
    public Set<Stock> getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set<Stock> stocks) {
        this.stocks = stocks;
    }
    public Set<SupplierHasStock> getSupplierHasStocks() {
        return this.supplierHasStocks;
    }
    
    public void setSupplierHasStocks(Set<SupplierHasStock> supplierHasStocks) {
        this.supplierHasStocks = supplierHasStocks;
    }
    public Set<Supplierverificationcode> getSupplierverificationcodes() {
        return this.supplierverificationcodes;
    }
    
    public void setSupplierverificationcodes(Set<Supplierverificationcode> supplierverificationcodes) {
        this.supplierverificationcodes = supplierverificationcodes;
    }
    public Set<SupplierHasDeliverydistrict> getSupplierHasDeliverydistricts() {
        return this.supplierHasDeliverydistricts;
    }
    
    public void setSupplierHasDeliverydistricts(Set<SupplierHasDeliverydistrict> supplierHasDeliverydistricts) {
        this.supplierHasDeliverydistricts = supplierHasDeliverydistricts;
    }
    public Set<Supplierlogin> getSupplierlogins() {
        return this.supplierlogins;
    }
    
    public void setSupplierlogins(Set<Supplierlogin> supplierlogins) {
        this.supplierlogins = supplierlogins;
    }
    public Set<Supplierpayment> getSupplierpayments() {
        return this.supplierpayments;
    }
    
    public void setSupplierpayments(Set<Supplierpayment> supplierpayments) {
        this.supplierpayments = supplierpayments;
    }
    public Set<SupplierHasRecoverquestion> getSupplierHasRecoverquestions() {
        return this.supplierHasRecoverquestions;
    }
    
    public void setSupplierHasRecoverquestions(Set<SupplierHasRecoverquestion> supplierHasRecoverquestions) {
        this.supplierHasRecoverquestions = supplierHasRecoverquestions;
    }




}


