package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * SupplierHasStock generated by hbm2java
 */
public class SupplierHasStock  implements java.io.Serializable {


     private Integer supplierHasStockid;
     private Supplier supplier;
     private Stock stock;
     private Date date;
     private Date time;
     private Double qty;

    public SupplierHasStock() {
    }

	
    public SupplierHasStock(Supplier supplier, Stock stock) {
        this.supplier = supplier;
        this.stock = stock;
    }
    public SupplierHasStock(Supplier supplier, Stock stock, Date date, Date time, Double qty) {
       this.supplier = supplier;
       this.stock = stock;
       this.date = date;
       this.time = time;
       this.qty = qty;
    }
   
    public Integer getSupplierHasStockid() {
        return this.supplierHasStockid;
    }
    
    public void setSupplierHasStockid(Integer supplierHasStockid) {
        this.supplierHasStockid = supplierHasStockid;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }




}


