package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * SupplierHasDeliverydistrict generated by hbm2java
 */
public class SupplierHasDeliverydistrict  implements java.io.Serializable {


     private Integer supplierHasDeliveryDistrictid;
     private Deliverydistrict deliverydistrict;
     private Supplier supplier;
     private Set<SupplierHasDeliverydistrictHasStock> supplierHasDeliverydistrictHasStocks = new HashSet<SupplierHasDeliverydistrictHasStock>(0);

    public SupplierHasDeliverydistrict() {
    }

	
    public SupplierHasDeliverydistrict(Deliverydistrict deliverydistrict, Supplier supplier) {
        this.deliverydistrict = deliverydistrict;
        this.supplier = supplier;
    }
    public SupplierHasDeliverydistrict(Deliverydistrict deliverydistrict, Supplier supplier, Set<SupplierHasDeliverydistrictHasStock> supplierHasDeliverydistrictHasStocks) {
       this.deliverydistrict = deliverydistrict;
       this.supplier = supplier;
       this.supplierHasDeliverydistrictHasStocks = supplierHasDeliverydistrictHasStocks;
    }
   
    public Integer getSupplierHasDeliveryDistrictid() {
        return this.supplierHasDeliveryDistrictid;
    }
    
    public void setSupplierHasDeliveryDistrictid(Integer supplierHasDeliveryDistrictid) {
        this.supplierHasDeliveryDistrictid = supplierHasDeliveryDistrictid;
    }
    public Deliverydistrict getDeliverydistrict() {
        return this.deliverydistrict;
    }
    
    public void setDeliverydistrict(Deliverydistrict deliverydistrict) {
        this.deliverydistrict = deliverydistrict;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public Set<SupplierHasDeliverydistrictHasStock> getSupplierHasDeliverydistrictHasStocks() {
        return this.supplierHasDeliverydistrictHasStocks;
    }
    
    public void setSupplierHasDeliverydistrictHasStocks(Set<SupplierHasDeliverydistrictHasStock> supplierHasDeliverydistrictHasStocks) {
        this.supplierHasDeliverydistrictHasStocks = supplierHasDeliverydistrictHasStocks;
    }




}


