package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0



/**
 * SupplierHasRecoverquestion generated by hbm2java
 */
public class SupplierHasRecoverquestion  implements java.io.Serializable {


     private Integer idSupplierHasRecoverQuestion;
     private Supplier supplier;
     private Recoverquestion recoverquestion;
     private String answer;

    public SupplierHasRecoverquestion() {
    }

	
    public SupplierHasRecoverquestion(Supplier supplier, Recoverquestion recoverquestion) {
        this.supplier = supplier;
        this.recoverquestion = recoverquestion;
    }
    public SupplierHasRecoverquestion(Supplier supplier, Recoverquestion recoverquestion, String answer) {
       this.supplier = supplier;
       this.recoverquestion = recoverquestion;
       this.answer = answer;
    }
   
    public Integer getIdSupplierHasRecoverQuestion() {
        return this.idSupplierHasRecoverQuestion;
    }
    
    public void setIdSupplierHasRecoverQuestion(Integer idSupplierHasRecoverQuestion) {
        this.idSupplierHasRecoverQuestion = idSupplierHasRecoverQuestion;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public Recoverquestion getRecoverquestion() {
        return this.recoverquestion;
    }
    
    public void setRecoverquestion(Recoverquestion recoverquestion) {
        this.recoverquestion = recoverquestion;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }




}


