package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Supplierlogin generated by hbm2java
 */
public class Supplierlogin  implements java.io.Serializable {


     private Integer idSupplierLogin;
     private Loginstatus loginstatus;
     private Supplier supplier;
     private String username;
     private String password;
     private Set<Supplierloggingsession> supplierloggingsessions = new HashSet<Supplierloggingsession>(0);

    public Supplierlogin() {
    }

	
    public Supplierlogin(Loginstatus loginstatus, Supplier supplier) {
        this.loginstatus = loginstatus;
        this.supplier = supplier;
    }
    public Supplierlogin(Loginstatus loginstatus, Supplier supplier, String username, String password, Set<Supplierloggingsession> supplierloggingsessions) {
       this.loginstatus = loginstatus;
       this.supplier = supplier;
       this.username = username;
       this.password = password;
       this.supplierloggingsessions = supplierloggingsessions;
    }
   
    public Integer getIdSupplierLogin() {
        return this.idSupplierLogin;
    }
    
    public void setIdSupplierLogin(Integer idSupplierLogin) {
        this.idSupplierLogin = idSupplierLogin;
    }
    public Loginstatus getLoginstatus() {
        return this.loginstatus;
    }
    
    public void setLoginstatus(Loginstatus loginstatus) {
        this.loginstatus = loginstatus;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<Supplierloggingsession> getSupplierloggingsessions() {
        return this.supplierloggingsessions;
    }
    
    public void setSupplierloggingsessions(Set<Supplierloggingsession> supplierloggingsessions) {
        this.supplierloggingsessions = supplierloggingsessions;
    }




}


