package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Userstatus generated by hbm2java
 */
public class Userstatus  implements java.io.Serializable {


     private Integer idUserStatus;
     private String userStatus;
     private Set<Client> clients = new HashSet<Client>(0);
     private Set<Supplier> suppliers = new HashSet<Supplier>(0);

    public Userstatus() {
    }

    public Userstatus(String userStatus, Set<Client> clients, Set<Supplier> suppliers) {
       this.userStatus = userStatus;
       this.clients = clients;
       this.suppliers = suppliers;
    }
   
    public Integer getIdUserStatus() {
        return this.idUserStatus;
    }
    
    public void setIdUserStatus(Integer idUserStatus) {
        this.idUserStatus = idUserStatus;
    }
    public String getUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus;
    }
    public Set<Client> getClients() {
        return this.clients;
    }
    
    public void setClients(Set<Client> clients) {
        this.clients = clients;
    }
    public Set<Supplier> getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Set<Supplier> suppliers) {
        this.suppliers = suppliers;
    }




}


