package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0



/**
 * Userverificationcode generated by hbm2java
 */
public class Userverificationcode  implements java.io.Serializable {


     private Integer idUserVerificationCode;
     private Client client;
     private String code;
     private String codestatus;

    public Userverificationcode() {
    }

	
    public Userverificationcode(Client client) {
        this.client = client;
    }
    public Userverificationcode(Client client, String code, String codestatus) {
       this.client = client;
       this.code = code;
       this.codestatus = codestatus;
    }
   
    public Integer getIdUserVerificationCode() {
        return this.idUserVerificationCode;
    }
    
    public void setIdUserVerificationCode(Integer idUserVerificationCode) {
        this.idUserVerificationCode = idUserVerificationCode;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getCodestatus() {
        return this.codestatus;
    }
    
    public void setCodestatus(String codestatus) {
        this.codestatus = codestatus;
    }




}


