package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0



/**
 * Watchlist generated by hbm2java
 */
public class Watchlist  implements java.io.Serializable {


     private Integer idWatchList;
     private Client client;
     private Stock stock;

    public Watchlist() {
    }

    public Watchlist(Client client, Stock stock) {
       this.client = client;
       this.stock = stock;
    }
   
    public Integer getIdWatchList() {
        return this.idWatchList;
    }
    
    public void setIdWatchList(Integer idWatchList) {
        this.idWatchList = idWatchList;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }




}


