package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Watchshape generated by hbm2java
 */
public class Watchshape  implements java.io.Serializable {


     private Integer idWatchShape;
     private String watchShape;
     private Set<Product> products = new HashSet<Product>(0);

    public Watchshape() {
    }

    public Watchshape(String watchShape, Set<Product> products) {
       this.watchShape = watchShape;
       this.products = products;
    }
   
    public Integer getIdWatchShape() {
        return this.idWatchShape;
    }
    
    public void setIdWatchShape(Integer idWatchShape) {
        this.idWatchShape = idWatchShape;
    }
    public String getWatchShape() {
        return this.watchShape;
    }
    
    public void setWatchShape(String watchShape) {
        this.watchShape = watchShape;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


