package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Waterresistency generated by hbm2java
 */
public class Waterresistency  implements java.io.Serializable {


     private Integer idWaterResistency;
     private String rate;
     private Set<Product> products = new HashSet<Product>(0);

    public Waterresistency() {
    }

    public Waterresistency(String rate, Set<Product> products) {
       this.rate = rate;
       this.products = products;
    }
   
    public Integer getIdWaterResistency() {
        return this.idWaterResistency;
    }
    
    public void setIdWaterResistency(Integer idWaterResistency) {
        this.idWaterResistency = idWaterResistency;
    }
    public String getRate() {
        return this.rate;
    }
    
    public void setRate(String rate) {
        this.rate = rate;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


