package pojos;
// Generated Jul 27, 2017 7:58:58 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Weight generated by hbm2java
 */
public class Weight  implements java.io.Serializable {


     private Integer idWeight;
     private Double weight;
     private Set<Product> products = new HashSet<Product>(0);

    public Weight() {
    }

    public Weight(Double weight, Set<Product> products) {
       this.weight = weight;
       this.products = products;
    }
   
    public Integer getIdWeight() {
        return this.idWeight;
    }
    
    public void setIdWeight(Integer idWeight) {
        this.idWeight = idWeight;
    }
    public Double getWeight() {
        return this.weight;
    }
    
    public void setWeight(Double weight) {
        this.weight = weight;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


